server:
  port: 9124
  servlet:
    context-path: /robooot

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: wx
    password: Wx@20190818
    platform: mysql


mybatis:
  mapper-locations:
    - classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.togo.wx

logging:
  level:
    mapping : debug
